### PR TITLE
Add working zuul config

### PR DESCRIPTION
**Pull request by outcatcher**
Depends-On: https://github.com/opentelekomcloud-infra/otc-zuul-jobs/pull/27

### CODE REVIEW

**Comment by gtema** [comment]
recheck

**Comment by outcatcher** [comment]
recheck

**Comment by outcatcher** [comment]
recheck

**Comment by outcatcher** [comment]
recheck

**Comment by outcatcher** [comment]
Converted to draft, as this PR contains 24h token :slightly_smiling_face:, so it can't be used as it is

**Review by lego963 — DISMISSED** [review]

**Review by lego963 — APPROVED** [review]

**Pull request merged**
