### PR TITLE
Remove available service restrictions

### PR DESCRIPTION
**Pull request by outcatcher**
Now any service listed in service catalog can be used

### CODE REVIEW

**Comment by outcatcher** [comment]
recheck

**Comment by outcatcher** [comment]
recheck

**Comment by outcatcher** [comment]
recheck

**Comment by outcatcher** [comment]
recheck

**Review by lego963 — DISMISSED** [review]

**Comment by outcatcher** [comment]
recheck

**Comment by lego963** [comment]
recheck

**Review by gtema — CHANGES_REQUESTED** [review]
wrong, you should not use the "test" job but a proper "simpleton" one

**Comment by outcatcher** [comment]
> wrong, you should not use the "test" job but a proper "simpleton" one

Got that change totally wrong :smile:

**Comment by gtema** [comment]
> > wrong, you should not use the "test" job but a proper "simpleton" one
> 
> Got that change totally wrong 😄

no problem

**Review by gtema — APPROVED** [review]

**Pull request merged**
