### PR TITLE
Add link to the usage example

### PR DESCRIPTION
**Pull request by outcatcher**

### CODE REVIEW

**Review by lego963 — DISMISSED** [review]

**Review by gtema — COMMENTED** [review]
best would be to move example to opentelekomcloud-blueprints org

**Comment by outcatcher** [comment]
@gtema I don't have permissions there

**Comment by gtema** [comment]
gitstyring ;-)

**Review by anton-sidelnikov — DISMISSED** [review]

**Comment by anton-sidelnikov** [comment]
> gitstyring ;-)

https://github.com/opentelekomcloud-infra/gitstyring/pull/31 ^-^

**Review by lego963 — APPROVED** [review]

**Review by anton-sidelnikov — APPROVED** [review]

**Pull request merged**
